# terminus_agent.py
import requests
from harbor.agents.base import BaseAgent
from typing import Optional

class YourTerminusAgent(BaseAgent):
    @staticmethod
    def name() -> str:
        return "terminus"

    @staticmethod
    def version() -> str:
        return "1.0"

    def __init__(self, model_name: str, logs_dir: Optional[str] = None, logger=None, **kwargs):
        super().__init__(model_name, **kwargs)
        self.api_url = "http://localhost:3000/api/terminus/analyze"
        self.logger = logger

    def setup(self) -> None:
        """Check if the Terminus Next.js API is running."""
        try:
            response = requests.get("http://localhost:3000", timeout=5)
            if response.status_code != 200 and self.logger:
                self.logger.warning(f"Terminus app not responding (status {response.status_code})")
        except requests.ConnectionError:
            if self.logger:
                self.logger.error("Cannot connect to Terminus API at http://localhost:3000")
                self.logger.error("Make sure you have run 'npm run dev' in another terminal!")

    def run(self, observation: str) -> str:
        """Main method called by Harbor on every turn."""
        try:
            payload = {
                "taskPrompt": observation,
                "modelName": self.model_name
            }
            response = requests.post(self.api_url, json=payload, timeout=120)
            response.raise_for_status()
            data = response.json()

            if not data.get("success"):
                error_msg = data.get("error", "Unknown error")
                if self.logger:
                    self.logger.error(f"Terminus API error: {error_msg}")
                return f"echo 'API error: {error_msg}'"

            # Correct extraction — your API returns { "success": true, "data": { "codeOutput": "..." } }
            code_output = data.get("data", {}).get("codeOutput", "").strip()

            if not code_output:
                if self.logger:
                    self.logger.warning("Empty codeOutput from Terminus API")
                return "echo 'No command generated by Terminus'"

            return code_output

        except requests.Timeout:
            if self.logger:
                self.logger.error("Timeout calling Terminus API")
            return "echo 'API timeout'"
        except requests.RequestException as e:
            if self.logger:
                self.logger.error(f"Network error: {e}")
            return "echo 'Network error'"
        except Exception as e:
            if self.logger:
                self.logger.error(f"Unexpected agent error: {e}")
            return "echo 'Agent crashed'"